CREATE TABLE contacts (
contactNO INT(5) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
dateContact DATE NOT NULL,
prenom VARCHAR(40) NOT NULL,
nom VARCHAR(40) NOT NULL,
tel VARCHAR(25) NOT NULL,
email VARCHAR(80) NOT NULL,
adresse1 VARCHAR(60) NULL,
adresse3 VARCHAR(60) NULL,
adresse4 VARCHAR(60) NULL,
message VARCHAR(4000) NOT NULL)
ENGINE INNODB;