CREATE TABLE utilisateursInformations (
email VARCHAR(80) NOT NULL PRIMARY KEY,
nom VARCHAR(40) NOT NULL,
prenom VARCHAR(40) NOT NULL,
majeur CHAR(1) NULL,
mineur CHAR(1) NULL,
nom2 VARCHAR(40) NULL,
prenom2 VARCHAR(40) NULL,
INDEX(nom(10)),
INDEX(prenom(10)))
ENGINE INNODB;